"""empty message

Revision ID: a0a3712e3a3b
Revises: 1f0a8070e33e
Create Date: 2020-09-15 23:31:31.131707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a3712e3a3b'
down_revision = '1f0a8070e33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'City', ['city_id'], ['id'])
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city_id')
    op.drop_table('City')
    # ### end Alembic commands ###
